import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, BriefcaseBusiness, CheckCircle2, Clock3, GraduationCap, LocateFixed, MapPin, Mic, Route, Sparkles, Volume2 } from 'lucide-react';
import { opportunities, qualifications, trainingCentres } from './recommendationEngine';
import { districtLocations, nearestPilotDistrict, supportedDistricts } from './location';

const fieldMeta = [
  ['name','Full name','text'], ['age','Age','number'], ['city','City / town','text'], ['district','District','select'], ['pincode','Pincode','text'],
  ['education','Highest education','education'], ['currentOccupation','Current occupation','text'],
  ['yearsExperience','Years of experience','number'], ['skills','Skills you already have','text'],
  ['familyOccupation','Family / traditional occupation','text'], ['interests','Work you enjoy','text'],
  ['preferredField','Preferred field','text'], ['employmentPreference','Livelihood preference','preference'],
  ['willingToRelocate','Travel / relocation','relocation'], ['mobilityConstraints','Mobility constraints','text'],
];
const districts = supportedDistricts.map(item=>item.name);
const education = [['none','No formal schooling'],['class5','Class 5'],['class8','Class 8'],['class10','Class 10'],['class12','Class 12'],['iti','ITI'],['diploma','Diploma'],['graduate','Graduate']];
const labels = Object.fromEntries(fieldMeta.map(([id,label]) => [id,label]));

function Input({ meta, value, onChange }) {
  const [id,label,type] = meta;
  if (type === 'select') return <label><span>{label}</span><select value={value || ''} onChange={e => onChange(id,e.target.value)}><option value="">Choose district</option>{districts.map(x => <option key={x}>{x}</option>)}</select></label>;
  if (type === 'education') return <label><span>{label}</span><select value={value || ''} onChange={e => onChange(id,e.target.value)}><option value="">Choose level</option>{education.map(([v,n]) => <option key={v} value={v}>{n}</option>)}</select></label>;
  if (type === 'preference') return <label><span>{label}</span><select value={value || ''} onChange={e => onChange(id,e.target.value)}><option value="">Choose preference</option><option value="job">Salaried job</option><option value="self">Self-employment</option><option value="both">Open to both</option></select></label>;
  if (type === 'relocation') return <label><span>{label}</span><select value={value || ''} onChange={e => onChange(id,e.target.value)}><option value="">Choose option</option><option value="yes">Can relocate</option><option value="limited">Can travel nearby</option><option value="no">Local opportunities only</option></select></label>;
  return <label><span>{label}</span><input type={type} value={value || ''} placeholder={label} onChange={e => onChange(id,e.target.value)}/></label>;
}

export function AssessmentForm({ profile, onChange, onComplete, onBack }) {
  const [draft,setDraft] = useState(profile);
  const update = (id,value) => { const next = {...draft,[id]:value}; setDraft(next); onChange(next); };
  const ready = ['name','age','district','education','currentOccupation','yearsExperience','skills','interests','preferredField','employmentPreference','willingToRelocate'].every(k => String(draft[k] || '').trim());
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>Back</button><div className="page-heading"><div><div className="eyebrow"><BriefcaseBusiness size={15}/>BENEFICIARY ASSESSMENT</div><h1>Tell us about your livelihood journey</h1><p>Use this simple form, or return and speak naturally with the AI counsellor.</p></div><span className="prototype-badge">Prototype assessment</span></div><section className="counsel-card"><div className="assessment-grid">{fieldMeta.map(meta => <Input key={meta[0]} meta={meta} value={draft[meta[0]]} onChange={update}/>)}</div><button className="primary" disabled={!ready} onClick={() => onComplete({...draft,consent:'yes'})}>Review my profile<ArrowRight size={18}/></button></section></main>;
}

function LocationCapture({ profile, onChange }) {
  const [status,setStatus] = useState('idle');
  const locate = () => {
    if (!navigator.geolocation) { setStatus('unsupported'); return; }
    setStatus('requesting');
    navigator.geolocation.getCurrentPosition(position => {
      const {latitude,longitude} = position.coords;
      const nearest = nearestPilotDistrict(latitude,longitude);
      onChange({...profile,city:profile.city||nearest.city,district:nearest.district,state:nearest.state,latitude,longitude,locationSource:'browser'});
      setStatus('captured');
    },() => setStatus('denied'),{enableHighAccuracy:false,timeout:10000,maximumAge:300000});
  };
  const manual = (key,value) => {
    const defaults = key === 'district' ? districtLocations[value] : null;
    onChange({...profile,[key]:value,...(defaults ? {city:profile.city||defaults.city,state:defaults.state,latitude:defaults.latitude,longitude:defaults.longitude} : {}),locationSource:'manual'});
  };
  return <section className="location-capture"><div><MapPin size={20}/><span><b>Use your location for nearby opportunities</b><small>We only use it to calculate nearby training and demo jobs.</small></span></div><button className="listen-button" onClick={locate} disabled={status==='requesting'}><LocateFixed size={17}/>{status==='requesting'?'Requesting permission…':'Use current location'}</button>{status==='captured'&&<p className="location-status">Location captured. Nearest pilot district: {profile.district}</p>}{(status==='denied'||status==='unsupported')&&<p className="location-status warning">Location access was unavailable. Enter city, district and pincode below.</p>}<div className="manual-location"><input value={profile.city||''} placeholder="City / town" onChange={e=>manual('city',e.target.value)}/><select value={profile.district||''} onChange={e=>manual('district',e.target.value)}><option value="">District</option>{districts.map(x=><option key={x}>{x}</option>)}</select><input value={profile.pincode||''} inputMode="numeric" maxLength="6" placeholder="Pincode" onChange={e=>manual('pincode',e.target.value.replace(/\D/g,''))}/></div></section>;
}

export function ProfileSummary({ profile, onChange, onAnalyse, onBack, speak }) {
  const [editing,setEditing] = useState('');
  const summary = `${profile.name} is ${profile.age} years old and lives in ${profile.district}. Current work: ${profile.currentOccupation}, with ${profile.yearsExperience} years of experience. Skills: ${profile.skills}. Interests: ${profile.interests}. Preferred field: ${profile.preferredField}. Preference: ${profile.employmentPreference}.`;
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>Back to conversation</button><div className="page-heading"><div><div className="eyebrow"><CheckCircle2 size={15}/>PROFILE CONFIRMATION</div><h1>Is this livelihood profile correct?</h1><p>Confirm the extracted occupation and skills before any recommendation is generated.</p></div><button className="listen-button" onClick={() => speak?.(summary)}><Volume2 size={18}/>Hear summary</button></div><LocationCapture profile={profile} onChange={onChange}/><section className="counsel-card"><div className="profile-summary-grid">{fieldMeta.map(meta => { const [id,label] = meta; return <div key={id}><span>{label}</span>{editing === id ? <div className="inline-edit"><Input meta={meta} value={profile[id]} onChange={(key,val) => onChange({...profile,[key]:val})}/><button onClick={() => setEditing('')}>Done</button></div> : <><b>{profile[id] || 'Not provided'}</b><button onClick={() => setEditing(id)}>Edit</button></>}</div> })}</div><div className="engine-note"><Sparkles size={19}/><div><b>Deterministic matching</b><p>Unrelated sectors are removed first. Only eligible, relevant pathways scoring at least 60% can appear.</p></div></div><button className="primary" onClick={onAnalyse}>Confirm and find pathways<ArrowRight size={18}/></button></section></main>;
}

export function LivelihoodRecommendations({ profile, ranked, onDetails, onRoadmap, onBack, speak }) {
  const narration = ranked.length ? `I found ${ranked.length} suitable pathways. Your top match is ${ranked[0].name}, with a ${ranked[0].score} percent match. ${ranked[0].reasons.join('. ')}.` : 'I could not find an eligible match in this prototype catalog. An official counsellor should review the profile.';
  useEffect(() => { const timer = setTimeout(() => speak?.(narration), 450); return () => clearTimeout(timer); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>Profile summary</button><div className="page-heading"><div><div className="eyebrow"><Sparkles size={15}/>DETERMINISTIC MATCHING</div><h1>Your livelihood pathways</h1><p>Eligible options ranked using your skills, interest, education, experience, district and preference.</p></div><button className="listen-button" onClick={() => speak?.(narration)}><Volume2 size={18}/>Listen</button></div><div className="profile-strip"><span><BriefcaseBusiness size={17}/>{profile.currentOccupation}</span><span><MapPin size={17}/>{profile.district}</span><span><GraduationCap size={17}/>{profile.education}</span></div><div className="pathway-list">{ranked.map((course,index) => <article className="pathway-card" key={course.id}><div className="pathway-rank">0{index+1}</div><div className="pathway-main"><div className="pathway-head"><span>{course.sector}</span><strong>{course.score}% match</strong></div><h2>{course.name}</h2><p className="pathway-type">{course.pathwayType} · NSQF Level {course.nsqfLevel}</p><ul>{course.reasons.slice(0,3).map(x => <li key={x}>{x}</li>)}</ul><div className="pathway-facts"><span><Clock3 size={15}/>{course.durationHours} hours</span><span><MapPin size={15}/>{course.trainingCentres[0]?.name || 'Centre mapping pending'}</span></div><div className="card-actions"><button onClick={() => onDetails(course)}>View details</button><button className="primary" onClick={() => onRoadmap(course)}>Build roadmap<ArrowRight size={16}/></button></div></div></article>)}</div><p className="catalog-warning">Prototype catalog for demonstration. Qualification and centre records must be verified with NQR/NCVET and authorised programme data before deployment.</p></main>;
}

export function RecommendationDetails({ course, onBack, onRoadmap, speak }) {
  if (!course) return null;
  const narration = `${course.name} is a ${course.pathwayType} pathway at NSQF level ${course.nsqfLevel}. ${course.reasons.join('. ')}. You will learn ${course.skillsGained.join(', ')}. Possible roles include ${course.jobRoles.join(', ')}.`;
  const groups = [['Why it fits',course.reasons],['Skills you will gain',course.skillsGained],['Current skill gaps',course.skillGaps],['Possible job roles',course.jobRoles],['Self-employment options',course.selfEmployment]];
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>All pathways</button><div className="detail-hero"><div><span>{course.sector} · {course.id}</span><h1>{course.name}</h1><p>{course.pathwayType} · NSQF Level {course.nsqfLevel} · {course.durationHours} hours</p><button className="listen-button" onClick={() => speak?.(narration)}><Volume2 size={17}/>Listen to this pathway</button></div><strong>{course.score}%<small>match</small></strong></div><div className="detail-grid">{groups.map(([title,items]) => <section className="counsel-card" key={title}><h3>{title}</h3><ul>{(items?.length ? items : ['No item recorded']).map(x => <li key={x}>{x}</li>)}</ul></section>)}<section className="counsel-card"><h3>Training centres near you</h3>{course.trainingCentres.length ? course.trainingCentres.map(c => <p key={c.id}><b>{c.name}</b><br/><span>{c.address} · {c.distanceKm} km</span></p>) : <p>Centre mapping is pending for this district.</p>}</section><section className="counsel-card"><h3>Local opportunity signal</h3>{course.opportunities.length ? course.opportunities.map(x => <p key={x.id}><b>{x.demand} demand</b> · {x.roles.join(', ')}</p>) : <p>No local demand row in the prototype dataset.</p>}</section></div><button className="primary" onClick={() => onRoadmap(course)}>Create career roadmap<ArrowRight size={18}/></button></main>;
}

export function CareerRoadmap({ profile, course, onBack, onSubmit, submitting, speak }) {
  const steps = [{title:'Your starting point',text:`${profile.currentOccupation}; ${profile.yearsExperience} years of experience`},{title:course.pathwayType,text:`Complete ${course.name} (${course.durationHours} hours)`},{title:'Certification',text:`Assessment for NSQF Level ${course.nsqfLevel}`},{title:'Livelihood outcome',text:profile.employmentPreference === 'self' ? course.selfEmployment.join(' or ') : course.jobRoles.join(' or ')},{title:'Future upskilling',text:`Progress to an advanced ${course.sector} role after workplace experience`}];
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>Pathway details</button><div className="page-heading"><div><div className="eyebrow"><Route size={15}/>MY CAREER ROADMAP</div><h1>A practical route from skill to livelihood</h1><p>{course.name} · created from the confirmed profile</p></div><button className="listen-button" onClick={() => speak?.(steps.map((step,i) => `Step ${i+1}: ${step.title}. ${step.text}`).join('. '))}><Volume2 size={18}/>Listen to roadmap</button></div><div className="roadmap">{steps.map((step,i) => <article key={step.title}><span>{i+1}</span><div><small>STEP {i+1}</small><h3>{step.title}</h3><p>{step.text}</p></div></article>)}</div><button className="primary" disabled={submitting} onClick={onSubmit}>{submitting ? 'Saving roadmap…' : 'Save beneficiary roadmap'}<ArrowRight size={18}/></button></main>;
}

export function CounsellorAdmin({ profile, ranked, reference, onBack }) {
  const metrics = useMemo(() => ({assessments:128,eligible:104,rpl:37,districts:6,centres:trainingCentres.length,qualifications:qualifications.length,opportunities:opportunities.length}),[]);
  return <main className="dashboard counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>Back to beneficiary view</button><div className="page-heading"><div><div className="eyebrow"><BarChart3 size={15}/>PROGRAMME VIEW</div><h1>PM-AJAY livelihood dashboard</h1><p>Prototype monitoring view for officials and counsellors.</p></div><span className="prototype-badge">Demo data</span></div><section className="stat-grid"><div><span>ASSESSMENTS</span><b>{metrics.assessments}</b><small>Beneficiaries profiled</small></div><div><span>ELIGIBLE MATCHES</span><b>{metrics.eligible}</b><small>Across pathways</small></div><div><span>RPL PATHWAYS</span><b>{metrics.rpl}</b><small>Experience recognised</small></div><div><span>DISTRICTS</span><b>{metrics.districts}</b><small>Tamil Nadu pilot</small></div></section><div className="dashboard-grid"><section className="dash-card"><h2>Catalog readiness</h2><p>{metrics.qualifications} qualifications · {metrics.centres} centres · {metrics.opportunities} demand signals</p><div className="engine-note"><Sparkles size={18}/><p>All records are marked unverified prototype data. Production import requires official validation.</p></div></section><section className="dash-card"><h2>Current beneficiary</h2><p><b>{profile.name || 'No active assessment'}</b></p><p>{profile.district} · {profile.currentOccupation}</p><p>{ranked[0] ? `Top pathway: ${ranked[0].name} (${ranked[0].score}%)` : 'No matching run yet'}</p><p>{reference ? `Roadmap reference: ${reference}` : 'Roadmap not saved'}</p></section><section className="dash-card scoring-card"><h2>Explainable ranking</h2>{ranked.map((x,i) => <div className="score-row" key={x.id}><span className="rank">0{i+1}</span><div><b>{x.name}</b><small>{x.pathwayType}</small><div className="score-bar"><i style={{width:`${x.score}%`}}/></div></div><strong>{x.score}</strong></div>)}</section></div></main>;
}
