import { useEffect } from 'react';
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Clock3, MapPin, Route, Sparkles, Volume2 } from 'lucide-react';

export function OpportunityRecommendations({profile,ranked,onDetails,onRoadmap,onBack,speak}) {
  const narration=ranked.length?`I found ${ranked.length} relevant livelihood pathways. Your strongest match is ${ranked[0].name} at ${ranked[0].score} percent affinity. ${ranked[0].reasons.join('. ')}.`:'No relevant eligible pathway reached the sixty percent threshold. Unrelated sectors have been hidden.';
  useEffect(()=>{const timer=setTimeout(()=>speak?.(narration),450);return()=>clearTimeout(timer)},[]); // eslint-disable-line react-hooks/exhaustive-deps
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>Profile summary</button><div className="page-heading"><div><div className="eyebrow"><Sparkles size={15}/>LOCATION-AWARE LIVELIHOOD PLANNING</div><h1>Your livelihood pathways</h1><p>Only relevant, eligible pathways with at least 60% affinity are shown.</p></div><button className="listen-button" onClick={()=>speak?.(narration)}><Volume2 size={18}/>Listen</button></div><section className="where-now"><small>1 · WHERE YOU ARE NOW</small><h2>{profile.currentOccupation} · {profile.yearsExperience} years</h2><p>{profile.skills} · interested in {profile.interests} · {profile.city||profile.district}</p></section>{!ranked.length&&<section className="no-match"><h2>No relevant pathway reached 60%</h2><p>Unrelated courses were filtered out. Review the occupation, experience, skills, education and interests or request counsellor support.</p></section>} {!!ranked.length&&<div className="section-label">2 · BEST OPPORTUNITIES FOR YOU</div>}<div className="pathway-list">{ranked.map((course,index)=><article className="pathway-card" key={course.id}><div className="pathway-rank">0{index+1}</div><div className="pathway-main"><div className="pathway-head"><span>{course.sector}</span><strong>{course.score}% affinity</strong></div><h2>{course.name}</h2><p className="pathway-type">{course.pathwayType} · NSQF Level {course.nsqfLevel}</p><ul>{course.reasons.slice(0,4).map(x=><li key={x}>{x}</li>)}</ul><div className="score-breakdown">{Object.entries(course.breakdown).map(([key,value])=><span key={key}><small>{key.replace(/([A-Z])/g,' $1')}</small><b>{value}</b></span>)}</div><div className="pathway-facts"><span><Clock3 size={15}/>{course.durationHours} hours</span><span><MapPin size={15}/>{course.trainingCentres[0]?.name||'Centre mapping pending'}</span><span><BriefcaseBusiness size={15}/>{course.jobs.length} demo jobs mapped</span></div><div className="card-actions"><button className="primary" onClick={()=>onDetails(course)}>Answer my four questions<ArrowRight size={16}/></button><button onClick={()=>onRoadmap(course)}>View progression</button></div></div></article>)}</div><p className="catalog-warning">Prototype/demo records only. Qualifications, centres, demand and jobs require official verification before deployment. No salary increase is guaranteed.</p></main>;
}

export function OpportunityDetails({course,onBack,onRoadmap,speak}) {
  if(!course)return null;
  const narration=`${course.name}. ${course.reasons.join('. ')}. Learn ${course.skillGaps.join(', ')}. Possible work includes ${course.jobRoles.join(', ')}.`;
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>All pathways</button><div className="detail-hero"><div><span>{course.sector} · {course.id}</span><h1>{course.name}</h1><p>{course.pathwayType} · NSQF Level {course.nsqfLevel} · {course.durationHours} hours</p><button className="listen-button" onClick={()=>speak?.(narration)}><Volume2 size={17}/>Listen</button></div><strong>{course.score}%<small>affinity</small></strong></div><div className="four-answers"><section><small>WHAT CAN I DO?</small><h3>{course.jobRoles.join(' or ')}</h3><p>{course.reasons.join('. ')}.</p></section><section><small>WHAT SHOULD I LEARN NEXT?</small><h3>{course.pathwayType}</h3><p>{course.skillGaps.join(', ')}</p></section><section><small>WHERE CAN I LEARN IT NEAR ME?</small><h3>{course.trainingCentres[0]?.name||'Official centre mapping required'}</h3><p>{course.trainingCentres[0]?`${course.trainingCentres[0].address} · ${course.trainingCentres[0].distanceKm} km`:'No relevant prototype centre is mapped.'}</p></section><section><small>WHERE CAN THIS SKILL HELP ME EARN?</small><h3>{course.jobs[0]?.title||course.jobRoles[0]}</h3><p>{course.jobs[0]?`${course.jobs[0].employer} · ${course.jobs[0].city} · ${course.jobs[0].distanceKm} km`:'No nearby prototype job record is mapped.'}</p></section></div><div className="detail-grid"><Info title="3 · Why this suits you" items={course.reasons}/><section className="counsel-card"><h3>4 · Skill gap</h3><b>You already know</b><ul>{course.knownSkills.map(x=><li key={x}>{x}</li>)}</ul><b>Learn next</b><ul>{course.skillGaps.map(x=><li key={x}>{x}</li>)}</ul></section><section className="counsel-card"><h3>5 · Training near you</h3>{course.trainingCentres.length?course.trainingCentres.map(c=><p key={c.id}><b>{c.name}</b><br/>{c.address} · {c.distanceKm} km<br/><small>Prototype/demo centre</small></p>):<p>No relevant prototype centre mapped.</p>}</section><section className="counsel-card"><h3>6 · Jobs near you</h3>{course.jobs.length?course.jobs.map(job=><p key={job.id}><b>{job.title}</b><br/>{job.employer} · {job.city} · {job.distanceKm} km<br/><small>Prototype/demo opportunity</small></p>):<p>No relevant prototype job mapped.</p>}</section><section className="counsel-card"><h3>7 · Self-employment possibility</h3>{course.selfEmploymentFit.length?<ul>{course.selfEmploymentFit.map(x=><li key={x}>{x}</li>)}</ul>:<p>Your confirmed preference is wage employment. These options can be reconsidered if your goal changes.</p>}</section><section className="counsel-card"><h3>8 · Expected progression</h3><p className="progression-line">{course.progression.join(' → ')}</p><small>No guaranteed salary or income claim is made.</small></section></div><button className="primary" onClick={()=>onRoadmap(course)}>Open personalized progression<ArrowRight size={18}/></button></main>;
}

function Info({title,items}) { return <section className="counsel-card"><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></section> }

export function PersonalizedRoadmap({profile,course,onBack,onSubmit,submitting,speak}) {
  if(!course)return null;
  const steps=course.progression.map((text,index)=>({title:['Where you are now','Best next intervention','Qualification / certification','Livelihood opportunity','Future progression'][index],text}));
  const narration=steps.map((step,index)=>`Step ${index+1}. ${step.title}. ${step.text}`).join('. ');
  return <main className="content-page counsel-page"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/>Pathway details</button><div className="page-heading"><div><div className="eyebrow"><Route size={15}/>PERSONALIZED LIVELIHOOD PROGRESSION</div><h1>{profile.currentOccupation} to {course.jobRoles[0]}</h1><p>Built from the confirmed profile—not a generic template.</p></div><button className="listen-button" onClick={()=>speak?.(narration)}><Volume2 size={18}/>Listen</button></div><div className="roadmap">{steps.map((step,index)=><article key={step.title}><span>{index+1}</span><div><small>STEP {index+1}</small><h3>{step.title}</h3><p>{step.text}</p></div></article>)}</div><div className="catalog-warning">Income improvement is a goal, not a guarantee. No salary range is shown because this prototype has no verified wage source.</div><button className="primary" disabled={submitting} onClick={onSubmit}>{submitting?'Saving roadmap…':'Save beneficiary roadmap'}<ArrowRight size={18}/></button></main>;
}
